name: Update XML Feed

on:
  schedule:
      - cron: '0 2,11,15 * * *' # # Запуск в 05:00, 14:00 и 18:00 по Киевскому времени
  workflow_dispatch: # Позволяет запускать скрипт вручную по кнопке

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add my_prom_feed.xml
          git commit -m "Автоматическое обновление прайса" || exit 0
          git pull --rebase origin main
          git push
